# Generated by Django 4.2 on 2024-09-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_hashtag_post_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="posts_hashtags", to="posts.hashtag"
            ),
        ),
    ]
