# Generated by Django 4.2 on 2024-10-02 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0002_article_likes_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="likes_count",
        ),
        migrations.AddField(
            model_name="article",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_articles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
