# Generated by Django 4.2 on 2024-10-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_likes_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="likes_count",
        ),
    ]
