# Generated by Django 4.2 on 2024-10-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_product_delete_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
