# Generated by Django 4.2 on 2024-09-26 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_emailverification"),
        ("accounts", "0004_remove_userprofile_profile_picture_and_more"),
    ]

    operations = []
